import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Head from 'next/head';

import Navbar from './components/Navbar';
import Footer from './components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Headless CMS',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='en' className="scroll-smooth">
      <Head>
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <body className={`text-black h-full bg-white`}>
        <Navbar />
        <main className={'max-w-container mx-auto h-full bg-gradient-to-b from-light_gray via-10% via-white  to-light_gray'}>
          {children}
          </main>
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
